const N=256, INF=1e6;
const $=s=>document.querySelector(s), glyph=$('#glyph'), fusion=$('#fusion'), frame=$('#frame'), guard=$('#guard');
const scratch=document.createElement('canvas'); scratch.width=scratch.height=N; const sx=scratch.getContext('2d',{willReadFrequently:true});

function raster(text,font){sx.clearRect(0,0,N,N);sx.fillStyle='#fff';sx.textAlign='center';sx.textBaseline='middle';sx.font=font;sx.fillText(text,N/2,N/2+8);const d=sx.getImageData(0,0,N,N).data,m=new Uint8Array(N*N);for(let i=0;i<m.length;i++)m[i]=d[i*4+3]>96?1:0;return m}
function distance(seed){const d=new Float32Array(N*N);for(let i=0;i<d.length;i++)d[i]=seed[i]?0:INF;for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=y*N+x;d[i]=Math.min(d[i],x?d[i-1]+1:INF,y?d[i-N]+1:INF,x&&y?d[i-N-1]+1.414:INF,x<N-1&&y?d[i-N+1]+1.414:INF)}for(let y=N-1;y>=0;y--)for(let x=N-1;x>=0;x--){const i=y*N+x;d[i]=Math.min(d[i],x<N-1?d[i+1]+1:INF,y<N-1?d[i+N]+1:INF,x<N-1&&y<N-1?d[i+N+1]+1.414:INF,x&&y<N-1?d[i+N-1]+1.414:INF)}return d}
function sdf(mask){const inv=new Uint8Array(mask.length);for(let i=0;i<mask.length;i++)inv[i]=mask[i]?0:1;const a=distance(mask),b=distance(inv),s=new Float32Array(mask.length);for(let i=0;i<s.length;i++)s[i]=mask[i]?-b[i]:a[i];return s}
function exterior(mask){const seen=new Uint8Array(mask.length),q=[];for(let x=0;x<N;x++){q.push(x,(N-1)*N+x)}for(let y=0;y<N;y++){q.push(y*N,y*N+N-1)}for(let h=0;h<q.length;h++){const i=q[h];if(i<0||i>=mask.length||seen[i]||mask[i])continue;seen[i]=1;const x=i%N;if(x)q.push(i-1);if(x<N-1)q.push(i+1);if(i>=N)q.push(i-N);if(i<mask.length-N)q.push(i+N)}return seen}
function topology(mask){const seen=new Uint8Array(mask.length);let c=0;for(let i=0;i<mask.length;i++)if(mask[i]&&!seen[i]){c++;const q=[i];seen[i]=1;for(let h=0;h<q.length;h++){const j=q[h],x=j%N;for(const k of [x?j-1:-1,x<N-1?j+1:-1,j>=N?j-N:-1,j<mask.length-N?j+N:-1])if(k>=0&&mask[k]&&!seen[k]){seen[k]=1;q.push(k)}}}const ext=exterior(mask);let holes=0;const hs=new Uint8Array(mask.length);for(let i=0;i<mask.length;i++)if(!mask[i]&&!ext[i]&&!hs[i]){holes++;const q=[i];hs[i]=1;for(let h=0;h<q.length;h++){const j=q[h],x=j%N;for(const k of [x?j-1:-1,x<N-1?j+1:-1,j>=N?j-N:-1,j<mask.length-N?j+N:-1])if(k>=0&&!mask[k]&&!ext[k]&&!hs[k]){hs[k]=1;q.push(k)}}}return[c,holes]}
function paint(canvas,mask,color='#d8ff49'){const c=canvas.getContext('2d'),im=c.createImageData(N,N);for(let i=0;i<mask.length;i++){const on=mask[i],edge=on&&(!mask[i-1]||!mask[i+1]||!mask[i-N]||!mask[i+N]);const p=i*4;im.data[p]=edge?5:parseInt(color.slice(1,3),16);im.data[p+1]=edge?6:parseInt(color.slice(3,5),16);im.data[p+2]=edge?5:parseInt(color.slice(5,7),16);im.data[p+3]=on?255:0}c.clearRect(0,0,canvas.width,canvas.height);c.putImageData(im,0,0)}
function render(){const ch=[...glyph.value][0]||'あ',gm=raster(ch,'bold 210px sans-serif'),pm=raster(String.fromCodePoint(0xE000+Number(frame.value)),'220px "Party Parrot Frames"');const gs=sdf(gm),ps=sdf(pm),t=Number(fusion.value)/100,bias=(1-t)*75,k=9,out=new Uint8Array(N*N),holes=exterior(gm);let protectedCount=0;for(let i=0;i<out.length;i++){const a=gs[i],b=ps[i]+bias,m=-Math.log(Math.exp(-a/k)+Math.exp(-b/k))*k;let on=m<0;if(guard.checked&&!gm[i]&&!holes[i]){if(on)protectedCount++;on=false}out[i]=on?1:0}paint($('#glyphView'),gm,'#ff4d86');paint($('#parrotView'),pm,'#4deeea');const small=document.createElement('canvas');small.width=small.height=N;paint(small,out,'#d8ff49');const rc=$('#result').getContext('2d');rc.clearRect(0,0,512,512);rc.imageSmoothingEnabled=false;rc.drawImage(small,0,0,512,512);const [b0,b1]=topology(out);$('#beta0').textContent=b0;$('#beta1').textContent=b1;$('#guarded').textContent=protectedCount;$('#fusionValue').textContent=fusion.value;$('#frameValue').textContent=frame.value}
[glyph,fusion,frame,guard].forEach(el=>el.addEventListener('input',render));document.fonts.ready.then(render);
